### ISSUE TITLE
DevExtreme component library dxi-item, editorType="dxTextBox . How to customize the input class name  maybe id name

### ISSUE THREAD

**Issue by Dream-7d** [DevExpress-Examples/devextreme-dropdownbox-display-tags-in-input-field#3]
DevExtreme component library dxi-item, editorType="dxTextBox . How to customize the input class name  maybe id name

**Comment by LexDX** [comment]
Hi @Dream-7d,

If you have a specific technical question or need assistance with DevExtreme components, feel free to raise a ticket in our Support Center - [http://www.devexpress.com/ask](http://www.devexpress.com/ask). We will be happy to answer your technical inquiries there.
